### ISSUE TITLE
Add total value for stacked bar chart visualisation

### ISSUE THREAD

**Issue by Samodelov-SK** [nielsen-oss/superset-viz-plugins#24]
Hi, very interesting chart. Can you please add a total value of column for each bar chart column when multiple metrics are stacked? Including when are other visual styles for metrics used others bar chart?

**Comment by simchaNielsen** [comment]
@Samodelov-SK hi do you mean add total value to tooltip? 
Can you please add some screenshot and mark place where you want to add it? 
Thanks

**Comment by Samodelov-SK** [comment]
@simcha90 hi. When several columns are stacked into one, I would like to see the total sum of the entire column at the top.
Example:
Before
![now](https://user-images.githubusercontent.com/77116081/107140659-242d8900-6956-11eb-9ebf-c300e6fc4d28.jpg)

After:
![want](https://user-images.githubusercontent.com/77116081/107140843-a1a5c900-6957-11eb-8a4f-ec0d95f852a7.jpg)

Thanks

**Comment by simcha90** [comment]
hi @Samodelov-SK we added support for this feature for a simple case when you use only bar charts without customisation of chart types per metric, here: https://github.com/nielsen-oss/superset-viz-plugins/pull/35

For now we don't have in our roadmap to add this feature for multiple chart types per metric, but we are open for contributions :)
