### ISSUE TITLE
Not Working on new superset 1.3.0

### ISSUE THREAD

**Issue by aelich** [nielsen-oss/superset-viz-plugins#76]
When i run on new super set I get next ERR becuase in package.json it's forced 0.16.9

```
npm ERR! process terminated
npm ERR! signal SIGINT

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-01T18_13_06_947Z-debug.log
root@319cbbdd8f23:/app/superset-frontend# npm install @superset-viz-plugins/plugin-chart-waterfall
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: superset@0.0.0dev
npm ERR! Found: @superset-ui/chart-controls@0.17.85
npm ERR! node_modules/@superset-ui/chart-controls
npm ERR!   @superset-ui/chart-controls@"^0.17.85" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @superset-ui/chart-controls@"0.16.9" from @superset-viz-plugins/plugin-chart-composed@0.23.3
npm ERR! node_modules/@superset-viz-plugins/plugin-chart-composed
npm ERR!   @superset-viz-plugins/plugin-chart-composed@"^0.23.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.
```

Can you please update **superset-ui/chart-controls@"0.16.9"** and push to npm or should i use npm --force or --legacy-peer-deps? 

```
npm ci --legacy-peer-deps
```

Tried both `npm --force` and `npm --legacy-peer-deps` cannot make it work any more new search is now detecting them... Please help.

**Comment by aelich** [comment]
I made an issue on superset [Custom visualization doesn't work on superset 1.3.0](https://github.com/apache/superset/issues/16560#issue-985801487) but no answer still

**Comment by aelich** [comment]
Guys any help @amitmiran137 @MatanBobi @simcha90 I can code just pls give me some guides what to fix?

**Comment by MatanBobi** [comment]
@aelich it looks like all you need to do is to upgrade the `peerDependency` for `@superset-ui/chart-controls` to be `0.17^` since superset 1.3 is working with `chart-controls` version 0.17 and not 0.16.
Please tag this is a breaking change since this won't work in superset version 1.2.

**Comment by aelich** [comment]
@MatanBobi  I just cannot make it work i dont know why
"peerDependencies": {
    "@superset-ui/chart-controls": "^0.17.85",
    "@superset-ui/core": "0.16.7",
    "react": "^16.13.1"
  },
  
And i get 
![not_work](https://user-images.githubusercontent.com/41852883/134329326-5b4208f3-6afa-4c76-aa8b-3fa00e70407f.jpg)
 
Sill do i something wrong?

**Comment by MatanBobi** [comment]
@simcha90 did you try running the plugin in superset 1.3?

**Comment by aelich** [comment]
yes, now doing it on top of my EC2 machine I can give you IP http://3.68.21.76:8088/ to make sure I set it up as in: [Custom visualization doesn't work on superset 1.3.0](https://github.com/apache/superset/issues/16560#issue-985801487) and in 1.2.0 it was working now get errors..

I'm kinda desperate as need this one to close final release for customer..

**Comment by MatanBobi** [comment]
@aelich let's wait for @simcha90 to respond, he's usually the one in charge of the plugins :)

**Comment by aelich** [comment]
@MatanBobi Lets wait for @simcha90 i would deeply appreciate the help, even as in form that of instruction.. i can work but don’t understand too much about this issue now.

**Comment by aelich** [comment]
@MatanBobi I think i found issue its in transition form 0.16.10 -> 0.17.0 

![image](https://user-images.githubusercontent.com/41852883/134460074-f793a28e-7086-4fec-b912-3d811b517187.png)

[SUPER SET COMMIT API change to V1 ](https://github.com/apache-superset/superset-ui/commits/v0.17.0)

so here happened major version change in **API** 0.17-0.18 is nothing but 0.16 -> 0.17 is major change. Still researching about it, as I started using superset recently it's all slow for me.

**Comment by aelich** [comment]
@MatanBobi Superset 1.3.0 is sooo much more powerful and bug free and if could add your plugins it would be a dream come true... So thats why I spent 2 weeks trying to solve it..

**Comment by amitmiran137** [comment]
we will start addressing this and other issues next Wednesday

**Comment by HieuTrLuu** [comment]
I am also having this problem 
can u help @amitmiran137 ?

Much appreciated

**Comment by amitmiran137** [comment]
Do you work with the 1.3 in the superset repo? 
Currently this is what is supported by the Nielsen viz plugins

**Comment by aelich** [comment]
@amitmiran137 really, its supported on 1.3 can you pls send me how can i make it run, as i tried everything so far, and cannot do it in 1.3.0.. my approach was like https://github.com/apache/superset/issues/16560#issue-985801487 

please help!

**Comment by HieuTrLuu** [comment]
Hi @amitmiran137 
yes I am using the 1.3.0 version in the superset demo
I am also trying to fix it myself superset render React component to html, css so it is pretty hard for me to do debug atm :(

```
(base) ➜  superset git:(6d19de8f6) ✗ git status
HEAD detached at 1.3.0
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   superset-frontend/package-lock.json
	modified:   superset-frontend/package.json
	modified:   superset-frontend/src/visualizations/presets/MainPreset.js

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	superset-frontend/plugin-chart-composed/

no changes added to commit (use "git add" and/or "git commit -a")

```

**Comment by aelich** [comment]
@amitmiran137 @simcha90  @MatanBobi if its working pls just give me some hint how to run it, I'm kinda stuck, maybe i'm just stupid? Please, please guide me...

**Comment by aelich** [comment]
@amitmiran137 @simcha90  for  **"@superset-viz-plugins/plugin-chart-composed": "^0.31.0"** just tried 5-6 times to build always the same error:
```
ERROR in ./node_modules/@superset-viz-plugins/plugin-chart-composed/esm/components/icons.js
Module not found: Error: Can't resolve '../images/arrow-down.svg' in '/app/superset-frontend/node_modules/@superset-viz-plugins/plugin-chart-composed/esm/components'

ERROR in ./node_modules/@superset-viz-plugins/plugin-chart-composed/esm/components/icons.js
Module not found: Error: Can't resolve '../images/arrow-up.svg' in '/app/superset-frontend/node_modules/@superset-viz-plugins/plugin-chart-composed/esm/components'
```

![image](https://user-images.githubusercontent.com/41852883/137354334-1650db9a-fe50-4a62-8b3e-f0e952a12b09.png)

**Comment by simcha90** [comment]
> @amitmiran137 to reproduce 1/ click on "Charts" 2/ create new "+ chart" 3/ choose dataset "birth_names" 4/ Choose "Composed Chart" 5/ click "RAW RECORDS" (don't run "AGGREGATE" first, go straight to "raw records"!) 6/ chose x as "name" and y as "num_boys"
> 
> and error happens T_T
> 
> for "LEGEND" i cant make it to work..

https://github.com/nielsen-oss/superset-viz-plugins/pull/87 <- here the fix

**Comment by simcha90** [comment]
> @amitmiran137 @simcha90 for **"@superset-viz-plugins/plugin-chart-composed": "^0.31.0"** just tried 5-6 times to build always the same error:
> 
> ```
> ERROR in ./node_modules/@superset-viz-plugins/plugin-chart-composed/esm/components/icons.js
> Module not found: Error: Can't resolve '../images/arrow-down.svg' in '/app/superset-frontend/node_modules/@superset-viz-plugins/plugin-chart-composed/esm/components'
> 
> ERROR in ./node_modules/@superset-viz-plugins/plugin-chart-composed/esm/components/icons.js
> Module not found: Error: Can't resolve '../images/arrow-up.svg' in '/app/superset-frontend/node_modules/@superset-viz-plugins/plugin-chart-composed/esm/components'
> ```
> 
> ![image](https://user-images.githubusercontent.com/41852883/137354334-1650db9a-fe50-4a62-8b3e-f0e952a12b09.png)

1. Is it superset or storybook?
2. Did you try remove all node_modules and reinstall and then rebuild? @aelich 
3.

**Comment by nattapat0255** [comment]
I'm having trouble when I trying to add superset-viz-plugin to Superset following this tutorial: https://preset.io/blog/2020-07-02-hello-world/

In plugin-chart-hello-world it's working fine. But when I add some chart in superset-viz-plugin such as 'plugin-chart-composed' It's doesn't work. :(

please help!

```ERROR in ./src/visualizations/presets/MainPreset.js
Module not found: Error: Can't resolve '@superset-viz-plugins/plugin-chart-composed' in '/superset/superset-frontend/src/visualizations/presets'
ℹ ｢wdm｣: Failed to compile.
