### ISSUE TITLE
How do i add margin box in Composed Chart

### ISSUE THREAD

**Issue by nattapat0255** [nielsen-oss/superset-viz-plugins#90]
<img width="1436" alt="Screen Shot 2564-10-20 at 11 47 41" src="https://user-images.githubusercontent.com/81974292/138035153-f87148d5-9f0c-4822-9ea2-2d9cad694245.png">

From the image, I want to add a margin box because I want the name column displayed in one line.
How do I implement the code?

Please help!

**Comment by simcha90** [comment]
Meantime we don't have this feature, but on you own environment you can override css to add margin, Superset gives you opportunity to override css on dashboards and save this as metadata @nattapat0255
